version: '3'

services:
    wallet_ssikit:
        container_name: wallet_ssikit
        build:
            context: .
            dockerfile: ./docker/ssikit/Dockerfile
        tty: true
        volumes:
            - ./.docker/container_data:/container_data
        ports:
            - "7000:7000"
            - "7001:7001"
            - "7002:7002"
            - "7003:7003"
            - "7004:7004"
            - "7010:7010"
        networks:
            netw-wallet:
                aliases:
                    - wallet_ssikit

    wallet_ssikit_cli:
        container_name: wallet_ssikit_cli
        build:
            context: .
            dockerfile: ./docker/ssikit_cli/Dockerfile
        tty: true
        volumes:
            - ./.docker/container_data:/container_data
        networks:
            netw-wallet:
                aliases:
                    - wallet_ssikit_cli


networks:
    netw-wallet: